Repository woowa-techcamp-2021/baemin-17, pull requests merged in 2021-07, with the labels that each got.

#18 [Feature/agreement] 약관 페이지 기본 레이아웃 구성 및 라우팅 경로 추가
  public/images/cancel.svg
  public/images/right-arrow.svg
  public/stylesheets/agree.css
  public/stylesheets/style.css
  routes/index.js
  views/agree.pug
  views/layout.pug
Labels: enhancement

#21 [Feature/signup-detail] 회원가입-상세 페이지 기본 레이아웃 구성 및 경로 추가
  public/images/arrow-left.svg
  public/stylesheets/agree.css
  public/stylesheets/login.css
  public/stylesheets/signup-detail.css
  public/stylesheets/style.css
  routes/index.js
  views/agree.pug
  views/layout.pug
  views/login.pug
  views/signup-detail.pug
Labels: enhancement

#29 이미지 이름 한글 버그 수정
  public/images/arrow.png
  public/images/banner.png
  public/images/coupon.png
  public/images/heart.png
  public/images/order.png
  public/images/point.png
  public/images/present.png
  public/images/profile.png
  public/images/review.png
  public/images/sproud.png
  views/index.pug
Labels: bug

#25 [Feature/agreement-js] 약관 페이지 기획서 기능 요구사항 구현
  public/javascripts/agree.js
  public/stylesheets/agree.css
  public/stylesheets/style.css
  views/agree.pug
Labels: enhancement

#31 head block 추가 및 title 입력칸 변경
  routes/index.js
  views/layout.pug
Labels: enhancement

#27 [Feature/login-js] 로그인 페이지 기능 자바스크립트 처리
  public/javascripts/login.js
  public/stylesheets/login.css
  views/login.pug
Labels: enhancement

#33 [Feature/signup-detail-js] 회원가입 상세 페이지 기능 사항 구현
  public/javascripts/signup-detail.js
  public/stylesheets/signup-detail.css
  public/stylesheets/style.css
  views/signup-detail.pug
Labels: enhancement

#44 [bug/#40] 메인 페이지 로그인 링크를 수정
  views/index.pug
Labels: bug

#37 [Bug/#36] 로그인 페이지 로그인 버튼 CSS 미적용 수정
  public/javascripts/login.js
  views/login.pug
Labels: bug

#39 [bug/#38] 가입약관 페이지 다음버튼 클릭 시 휴대번호 페이지로 이동하도록 수정
  public/javascripts/agree.js
Labels: bug

#49 Revert "[bug/#40] 메인 페이지 로그인 링크를 수정"
  views/index.pug
Labels: bug

#50 [bugfix/#40] 메인 화면 로그인 버튼 링크 수정
  views/index.pug
Labels: bug

#42 [feature/#41] 회원가입 상세페이지 입력창 하이라이트 처리 기능 추가
  public/javascripts/signup-detail.js
  public/stylesheets/signup-detail.css
Labels: enhancement

#47 [refactor/#45] reset.css 추가로 인한 가입약관 페이지 스타일링 수정
  public/images/over.png
  public/images/under.png
  public/stylesheets/agree.css
  views/agree.pug
Labels: refactor

#51 [feature/#13] 회원가입 핸드폰 입력 페이지 js 기능 추가
  public/images/cancel-circle.png
  public/images/validation-green.png
  public/javascripts/signup-phone.js
  public/stylesheets/signup-phone.css
  views/layout.pug
  views/signup-phone.pug
Labels: enhancement

#52 [feature/#9-embedded db setting] 백엔드 DB 기본 세팅
  .gitignore
  db/database.js
  package-lock.json
  package.json
Labels: enhancement

#59 [feature/#58] bcrypt, express-session 추가
  package-lock.json
  package.json
Labels: enhancement

#61 [Bugfix/#60 promisify-db] 데이터베이스 조작 메서드 프라미스화
  db/database.js
Labels: bug

#62 [feature/#54] 회원가입 로직 구현 및 프론트엔드 단과 연결
  app.js
  public/javascripts/signup-detail.js
  routes/index.js
  views/signup-detail.pug
Labels: enhancement

#64 [bugfix/#63] 전체동의 버튼 활성화 관련 로직 버그 수정
  public/javascripts/agree.js
Labels: bug

#65 [feature/#56] 로그인 서버 기능 구현
  public/javascripts/login.js
  public/stylesheets/index.css
  public/stylesheets/login.css
  routes/index.js
  views/index.pug
  views/login.pug
Labels: enhancement

#69 [bugfix/#66] 회원가입 상세페이지 history.back 을 이용해 history.stack 문제 해결
  public/javascripts/signup-detail.js
  views/signup-detail.pug
Labels: bug

#68 [refactor/#43] 중복되는 레이아웃의 스타일링 통일화
  public/stylesheets/index.css
  public/stylesheets/signup-detail.css
  public/stylesheets/signup-phone.css
Labels: refactor

#71 [feature/#70] web font 적용
  public/stylesheets/style.css
Labels: enhancement

#72 [feature/#67] readme 초안 작성
  README.md
Labels: documentation

#73 [document/#67] 리드미 본인 파트 작성 및 gif 파일 추가
  README.md
Labels: documentation
